name: VR nus
analytics: {}
purpose:
  - type: contact
    url: 'mailto:INFO@VRNUS.COM'
    label: 'LET''S TALK '
  - type: contact
    url: 'tel:711276953'
    label: Call me during labor hours
github: true
description: This is an space for the most weird and exciting news about VR stuff.
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
navigation:
  - name: Worth it
    id: 65b15f43-39f9-49b8-b0a2-199bef1b4b19
    type: content
  - name: Hw
    id: a72c1dcd-6580-452b-9169-debf29bd48c3
    type: content
layout_spectrum: 0.4176863733742681
color:
  lightness: 0.5363616620505801
  brandColors:
    - '#F6F6F6'
    - '#0B0B0B'
    - '#2F2F2F'
    - '#515151'
    - '#9C9C9C'
  saturation: 0.718123145941276
  brandStrength: 0.2409262334523114
  rhythmicContrast: 0.6277633907797165
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b19f9e66-481d-4eac-826e-1776d2217930.png
content_rating:
  adult: false
typography_spectrum: 0.1866194737187153
opengraph: {}
title: VR NUS
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/987f7931-e3aa-4007-9eac-cef9ac1b17ad.png
