layout_spectrum: 0.7204839772810366
typography_spectrum: 0.38560847313217084
color:
  lightness: 0.3656682783178985
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  saturation: 0.162988095395267
  brandStrength: 0.2384366978717839
  rhythmicContrast: 0.2837539074667684
name: VR nus
analytics: {}
purpose:
  - type: contact
    url: 'mailto:INFO@VRNUS.COM'
    label: 'LET''S TALK '
  - type: contact
    url: 'tel:711276953'
    label: Call me during labor hours
github: true
description: This is an space for the most weird and exciting news about VR stuff.
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a83d116c-211e-4b92-b18d-1f2861488c92.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a83d116c-211e-4b92-b18d-1f2861488c92.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: Worth it
    id: 65b15f43-39f9-49b8-b0a2-199bef1b4b19
    type: content
  - name: Hw
    id: a72c1dcd-6580-452b-9169-debf29bd48c3
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b19f9e66-481d-4eac-826e-1776d2217930.png
content_rating:
  adult: false
opengraph: {}
title: VR NUS
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/987f7931-e3aa-4007-9eac-cef9ac1b17ad.png
